apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: navikt/syfoproxy:{{version}}
  port: 80
  team: teamsykefravr
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /isReady
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  vault:
    enabled: true
  ingresses:
    - "https://{{application_name}}.nais.oera-q.local"
