apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomockproxy
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: "docker.pkg.github.com/navikt/syfoproxy:{{tag}}"
  port: 80
  team: teamsykefravr
  liveness:
    path: /isAlive
    initialDelay: 0
    periodSeconds: 5
    timeout: 1
    failureThreshold: 3
  readiness:
    path: /isReady
    initialDelay: 0
    periodSeconds: 5
    timeout: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  vault:
    enabled: true
  ingresses:
    - "https://syfomockproxy.nais.oera-q.local"
    - "https://syfomockproxy-q.nav.no"
